#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Справочник статей CoA v3.12 (AOCG-AUP-SPR-01-2026) и его засев по орг.

94 статьи, org-копия у каждой организации. Источник — промпт FIN-01 v3.12;
данные перенесены КАК ЕСТЬ, ничего не переименовано.

⚠️ ЭТОТ СПИСОК НЕ ПЕРЕПЕЧАТЫВАЛСЯ РУКАМИ — он СГЕНЕРИРОВАН разбором
справочника-источника, и разбор проверен на известном ответе: семь
контрольных чисел самого справочника (всего 94 · групп 9 · резервов 8 ·
неденежных 1 · income 10 · balance 10 · distribution 17) сошлись, плюс
три мутации (убрать статью, задвоить код, снять флаг резерва) поймались.
Те же семь чисел стоят тестом в `tests/pg/test_fin_coa_live.py`: список
данных без прибора на него — это 94 возможности опечататься молча.

⚠️ ЧЕГО ЗАСЕВ НЕ ДЕЛАЕТ, И ЭТО ВАЖНО ЗНАТЬ ЗАРАНЕЕ: он ДОСЕВАЕТ
отсутствующие коды и НЕ ОБНОВЛЯЕТ изменившиеся названия. Значит переход
на будущую v3.13 — отдельная работа, а не «поправить список и перезапустить»:
статья, переименованная в справочнике, останется в базе под старым именем.

`kind` по разделам (правило справочника-источника, а не наше решение):
    I → income; II, III, V, VI → expense;
    IV → 4.1/4.2/4.5 income, 4.3/4.4/4.6 expense;
    VII → balance; VIII → distribution.
"""

from __future__ import annotations

ВЕРСИЯ = "3.12"

# (code, name_ru, name_en, note, section, kind, is_cash, is_group, is_reserve)
# position не хранится в этом кортеже намеренно: он равен номеру строки
# по порядку и вычисляется при засеве, поэтому разойтись с порядком не может.
СТАТЬИ = (
    # ── Раздел I ──
    (
        "1.1",
        "Генеральное проектирование",
        "Design Services (BIM)",
        "Договоры BIM",
        "I",
        "income",
        True,
        False,
        False,
    ),
    (
        "1.2",
        "Концепция архитектурная",
        "Concept Design (CNPT)",
        "Договоры CNPT",
        "I",
        "income",
        True,
        False,
        False,
    ),
    (
        "1.3",
        "Дизайн-проект",
        "Interior Design (DSGN)",
        "Договоры DSGN",
        "I",
        "income",
        True,
        False,
        False,
    ),
    (
        "1.4",
        "Архитектурные решения",
        "Architectural Design (AR)",
        "Договоры AR",
        "I",
        "income",
        True,
        False,
        False,
    ),
    (
        "1.5",
        "Конструктивные решения",
        "Structural Design (KR)",
        "Договоры KR",
        "I",
        "income",
        True,
        False,
        False,
    ),
    (
        "1.6",
        "Авторский надзор",
        "Author Supervision",
        "Отдельный договор или ДС",
        "I",
        "income",
        True,
        False,
        False,
    ),
    ("1.7", "Прочая выручка", "Other Revenue", "", "I", "income", True, False, False),
    # ── Раздел II ──
    (
        "2.1",
        "ФОТ проектировщиков",
        "Payroll (проектировщиков)",
        "Начислено",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.2",
        "Налоги с ФОТ проектировщиков",
        "Payroll Taxes (проектировщиков)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.3",
        "ФОТ УПР проектировщиков",
        "Mgmt Fee (проектировщиков)",
        "Начислено",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.4",
        "Налоги с ФОТ УПР проектировщиков",
        "Taxes on Mgmt Fee (проектировщиков)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.5",
        "Бонусы KPI производственного персонала",
        "KPI Bonuses — Production",
        "",
        "II",
        "expense",
        True,
        True,
        False,
    ),
    (
        "2.5.1",
        "Бонусы KPI руководителей проектов",
        "KPI Bonuses — Project Managers",
        "Начислено",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.5.2",
        "Бонусы KPI бригадиров",
        "KPI Bonuses — Brigadiers",
        "Начислено",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.5.3",
        "Бонусы KPI проектировщиков",
        "KPI Bonuses — Designers",
        "Начислено",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.6",
        "Налоги с бонусов KPI производственного персонала",
        "Taxes on KPI Bonuses — Production",
        "",
        "II",
        "expense",
        True,
        True,
        False,
    ),
    (
        "2.6.1",
        "Налоги с бонусов KPI руководителей проектов",
        "Taxes — KPI Bonuses (PM)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.6.2",
        "Налоги с бонусов KPI бригадиров",
        "Taxes — KPI Bonuses (Brigadiers)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.6.3",
        "Налоги с бонусов KPI проектировщиков",
        "Taxes — KPI Bonuses (Designers)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.7",
        "Субподряд ПД",
        "Subcontract — Project Design",
        "Стадия ПД",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.8",
        "Субподряд РД",
        "Subcontract — Working Design",
        "Стадия РД",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.9",
        "Субподряд прочие",
        "Subcontract — Other",
        "",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.10",
        "Банковские гарантии",
        "Bank Guarantees",
        "По проектам",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    (
        "2.11",
        "Прочие прямые затраты",
        "Other Direct Costs",
        "",
        "II",
        "expense",
        True,
        False,
        False,
    ),
    # ── Раздел III ──
    ("3.1", "Общехозяйственные", "G&A", "", "III", "expense", True, True, False),
    ("3.1.1", "Постоянные", "Fixed", "", "III", "expense", True, True, False),
    (
        "3.1.1.1",
        "ФОТ АУП",
        "Payroll (АУП)",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.2",
        "Налоги с ФОТ АУП",
        "Payroll Taxes (АУП)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.3",
        "ФОТ УПР АУП",
        "Mgmt Fee (АУП)",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.4",
        "Налоги с ФОТ УПР АУП",
        "Taxes on Mgmt Fee (АУП)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.5",
        "Бонусы KPI АУП",
        "KPI Bonuses (АУП)",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.6",
        "Налоги с бонусов KPI АУП",
        "Taxes on KPI Bonuses (АУП)",
        "НДФЛ, ОМС, ПФР, ФСС",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.7",
        "Аренда и коммунальные",
        "Rent & Utilities",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.8",
        "Связь и IT",
        "Communications & IT",
        "Без ПО-подписок — см. 3.1.1.15",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.9",
        "Банковское обслуживание",
        "Banking Fees",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.10",
        "Юридические услуги",
        "Legal Services",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.11",
        "Бухгалтерия",
        "Accounting",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.12",
        "Амортизация",
        "Depreciation",
        "Неденежная статья — в ДДС не отражается",
        "III",
        "expense",
        False,
        False,
        False,
    ),
    (
        "3.1.1.13",
        "HR",
        "HR",
        "HH.ru, обучения и т.д.",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.14",
        "Взносы СРО",
        "SRO Membership Fees",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.15",
        "ПО по подписке",
        "Software Subscriptions",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.1.16",
        "Страхование",
        "Insurance",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.2",
        "Условно-постоянные",
        "Semi-Variable",
        "",
        "III",
        "expense",
        True,
        True,
        False,
    ),
    (
        "3.1.2.1",
        "Корпоративные мероприятия",
        "Corporate Events",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.2.2",
        "Дни рождения",
        "Birthday Gifts",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.1.2.3",
        "Офисные расходы",
        "Office Expenses",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    ("3.1.2.4", "Резерв", "Reserve", "", "III", "expense", True, False, True),
    ("3.1.2.5", "Резерв", "Reserve", "", "III", "expense", True, False, True),
    ("3.1.2.6", "Резерв", "Reserve", "", "III", "expense", True, False, True),
    (
        "3.2",
        "Коммерческие",
        "Sales & Marketing",
        "",
        "III",
        "expense",
        True,
        True,
        False,
    ),
    (
        "3.2.1",
        "Маркетинг",
        "Marketing",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.2.2",
        "Представительские",
        "Entertainment",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    (
        "3.2.3",
        "Командировочные",
        "Travel & Business Trips",
        "Начислено",
        "III",
        "expense",
        True,
        False,
        False,
    ),
    ("3.2.4", "Резерв", "Reserve", "", "III", "expense", True, False, True),
    # ── Раздел IV ──
    (
        "4.1",
        "Процентные доходы по депозитам",
        "Interest Income — Deposits",
        "Доходы от размещения средств",
        "IV",
        "income",
        True,
        False,
        False,
    ),
    (
        "4.2",
        "Процентные доходы по займам выданным",
        "Interest Income — Loans Issued",
        "Доходы от размещения средств",
        "IV",
        "income",
        True,
        False,
        False,
    ),
    (
        "4.3",
        "Процентные расходы по займам полученным",
        "Interest Expense — Loans Received",
        "Расходы по займам",
        "IV",
        "expense",
        True,
        False,
        False,
    ),
    (
        "4.4",
        "Прочие внереализационные",
        "Other Non-Operating",
        "",
        "IV",
        "expense",
        True,
        False,
        False,
    ),
    (
        "4.5",
        "Штрафы и пени полученные",
        "Penalties Received",
        "Неустойки от контрагентов",
        "IV",
        "income",
        True,
        False,
        False,
    ),
    (
        "4.6",
        "Штрафы и пени уплаченные",
        "Penalties Paid",
        "Не уменьшают базу УСН — сверка с бухгалтером",
        "IV",
        "expense",
        True,
        False,
        False,
    ),
    # ── Раздел V ──
    (
        "5.1",
        "УСН",
        "Simplified Tax (USN)",
        "Ежеквартальный",
        "V",
        "expense",
        True,
        False,
        False,
    ),
    (
        "5.2",
        "Транспортный налог",
        "Transport Tax",
        "",
        "V",
        "expense",
        True,
        False,
        False,
    ),
    ("5.3", "НДС", "VAT", "", "V", "expense", True, False, False),
    # ── Раздел VI ──
    (
        "6.1",
        "Оборудование и техника",
        "Equipment",
        "Компьютеры, оргтехника",
        "VI",
        "expense",
        True,
        False,
        False,
    ),
    (
        "6.2",
        "Мебель и обустройство офиса",
        "Furniture & Fixtures",
        "",
        "VI",
        "expense",
        True,
        False,
        False,
    ),
    (
        "6.3",
        "Капитальный ремонт",
        "Leasehold Improvements",
        "",
        "VI",
        "expense",
        True,
        False,
        False,
    ),
    (
        "6.4",
        "Программное обеспечение бессрочное",
        "Software (Perpetual)",
        "Revit, AutoCAD и др.",
        "VI",
        "expense",
        True,
        False,
        False,
    ),
    # ── Раздел VII ──
    (
        "7.1",
        "Дебиторская задолженность",
        "Accounts Receivable (AR)",
        "Акт подписан, деньги не пришли",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.2",
        "Гарантийные удержания",
        "Retention",
        "До окончания гарантийного срока",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.3",
        "Выручка к признанию / НЗП",
        "WIP — Work in Progress",
        "Работы выполнены, акт не подписан",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.4",
        "Кредиторская задолженность",
        "Accounts Payable (AP)",
        "Затраты начислены, деньги не ушли",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.5",
        "Получение займов",
        "Loans Received",
        "Тело, не доход/расход",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.6",
        "Погашение займов полученных",
        "Repayment of Loans Received",
        "Тело, не доход/расход",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.7",
        "Выдача займов",
        "Loans Issued",
        "Тело, не доход/расход",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.8",
        "Возврат займов выданных",
        "Repayment of Loans Issued",
        "Тело, не доход/расход",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.9",
        "Размещение депозитов",
        "Deposits Placed",
        "Тело, не доход/расход",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    (
        "7.10",
        "Возврат депозитов",
        "Deposits Returned",
        "Тело, не доход/расход",
        "VII",
        "balance",
        True,
        False,
        False,
    ),
    # ── Раздел VIII ──
    (
        "8.1",
        "Выплата дивидендов",
        "Dividends Payment",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    (
        "8.2",
        "Выплаты в счёт дохода учредителя 1",
        "Founder 1 Income Payments",
        "",
        "VIII",
        "distribution",
        True,
        True,
        False,
    ),
    (
        "8.2.1",
        "Оплата со счёта компании в счёт дохода учредителя 1",
        "Account Payment — Founder 1",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    (
        "8.2.2",
        "Оплата с карты компании в счёт дохода учредителя 1",
        "Card Payment — Founder 1",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    (
        "8.2.3",
        "Оплата УПР в счёт дохода учредителя 1",
        "Mgmt Fee Payment — Founder 1",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    ("8.2.4", "Резерв", "Reserve", "", "VIII", "distribution", True, False, True),
    (
        "8.3",
        "Выплаты в счёт дохода учредителя 2",
        "Founder 2 Income Payments",
        "",
        "VIII",
        "distribution",
        True,
        True,
        False,
    ),
    (
        "8.3.1",
        "Оплата со счёта компании в счёт дохода учредителя 2",
        "Account Payment — Founder 2",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    (
        "8.3.2",
        "Оплата с карты компании в счёт дохода учредителя 2",
        "Card Payment — Founder 2",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    (
        "8.3.3",
        "Оплата УПР в счёт дохода учредителя 2",
        "Mgmt Fee Payment — Founder 2",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    ("8.3.4", "Резерв", "Reserve", "", "VIII", "distribution", True, False, True),
    (
        "8.4",
        "Выплаты прочие в счёт общего дохода",
        "Other Payments — Joint Income",
        "",
        "VIII",
        "distribution",
        True,
        True,
        False,
    ),
    (
        "8.4.1",
        "Покупка недвижимого имущества",
        "Real Estate Purchase",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    (
        "8.4.2",
        "Покупка движимого имущества",
        "Movable Property Purchase",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    (
        "8.4.3",
        "Оплата услуг и прочих расходов",
        "Services & Other Expenses",
        "Выплачено / начислено",
        "VIII",
        "distribution",
        True,
        False,
        False,
    ),
    ("8.4.4", "Резерв", "Reserve", "", "VIII", "distribution", True, False, True),
    ("8.5", "Резерв", "Reserve", "", "VIII", "distribution", True, False, True),
)

# Строка засева. Комментарии держатся НАД литералом, а не внутри: прибор
# `sql_check` готовит каждый INSERT приложения и нормализует его склейкой
# строк — `--` внутри съел бы остаток запроса, и сломалось бы в чужом месте.
ВСТАВКА = """
    INSERT INTO fin_coa_articles
        (org_id, code, name_ru, name_en, section, kind,
         is_cash, is_group, is_reserve, note, position, coa_version)
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
    WHERE NOT EXISTS (
        SELECT 1 FROM fin_coa_articles WHERE org_id = $1 AND code = $2
    )
"""


async def seed_coa_for_org(conn, org_id: int) -> int:
    """Засеять справочник организации. Возвращает число вставленных статей.

    Для уже засеянной организации — 0 и ни одной записи. Быстрый выход по
    счётчику нужен потому, что функция идёт при КАЖДОМ старте контейнера:
    без него это 94 запроса на каждую организацию каждый раз.
    """
    было = await conn.fetchval(
        "SELECT count(*) FROM fin_coa_articles WHERE org_id = $1", org_id
    )
    if было == len(СТАТЬИ):
        return 0

    await conn.executemany(
        ВСТАВКА,
        [
            (
                org_id,
                code,
                name_ru,
                name_en or None,
                section,
                kind,
                is_cash,
                is_group,
                is_reserve,
                note or None,
                позиция,
                ВЕРСИЯ,
            )
            for позиция, (
                code,
                name_ru,
                name_en,
                note,
                section,
                kind,
                is_cash,
                is_group,
                is_reserve,
            ) in enumerate(СТАТЬИ, start=1)
        ],
    )

    стало = await conn.fetchval(
        "SELECT count(*) FROM fin_coa_articles WHERE org_id = $1", org_id
    )
    return стало - было
